/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.example.patterns.Rectangle;

import java.util.List;

public class App {

    public static void main(String[] args) {
        List<String> pattern = new Rectangle().generatePattern();
        String join = String.join("\n", pattern);
        System.out.println(join);
    }
}
